### PR TITLE
remove e2str and str2e

### PR DESCRIPTION
**Pull request by tarekziade**
Get rid of those functions and use string-based Enums

### CODE REVIEW

**Comment by wangch079** [comment]
Consolidate comments from multiple PRs, here is the suggested implmentation from @tarekziade :

```python
>>> class JobStatus(Enum):
...     PENDING = "pending"
...     IN_PROGRESS = "in_progress"
...     CANCELING = "canceling"
...     CANCELED = "canceled"
...     SUSPENDED = "suspended"
...     COMPLETED = "completed"
...     ERROR = "error"
...     UNSET = None
... 
>>> JobStatus(None)
<JobStatus.UNSET: None>
>>> JobStatus.UNSET.value
>>> JobStatus("pending")
<JobStatus.PENDING: 'pending'>
>>> JobStatus.PENDING.value
'pending'
```

**Review by timgrein — COMMENTED** [review]
We probably want to have `UNSET` also in `FilteringValidationState`.

**Comment by wangch079** [comment]
> We probably want to have `UNSET` also in `FilteringValidationState`.

`UNSET` is likely to be present in every enum.

**Comment by wangch079** [comment]
🤦‍♂️  I didn't realized this is a PR. I thought it was an issue in https://github.com/elastic/enterprise-search-team, and that's why I put a comment here: https://github.com/elastic/connectors-python/pull/464#issuecomment-1429286586

**Review by wangch079 — COMMENTED** [review]
LGTM, probably can also add `UNSET` for enum in `connectors/filtering/validation` as suggested by @timgrein

**Review by artem-shelkovnikov — APPROVED** [review]

**Comment by artem-shelkovnikov** [comment]
Just a quick question - why not raise error instead of having UNSET?

**Comment by tarekziade** [comment]
> LGTM, probably can also add `UNSET` for enum in `connectors/filtering/validation` as suggested by @timgrein

it's already the case

**Pull request merged**
