### PR TITLE
Refactor validations

### PR DESCRIPTION
**Pull request by navarone-feekery**
Some misc changes based on previous PR comments to avoid creating tech debt.
- Replace ` with ' for error logging
- Move `is_value_empty` to Field
- Move `validate_field` to Field (now named `validate`)

#### Pre-Review Checklist
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)
- [x] Considered corresponding documentation changes
- [x] Contributed any configuration settings changes to the configuration reference

### CODE REVIEW

**Review by artem-shelkovnikov — COMMENTED** [review]
Should there be tests for this logic?

**Comment by navarone-feekery** [comment]
@artem-shelkovnikov these are covered by tests on the `check_valid` method, which will call these Field methods.

here: https://github.com/elastic/connectors-python/blob/ece71a94c87d0b39cfe8286fc3ad51e81b4155f9/connectors/tests/test_source.py#L339-L341
and
here: https://github.com/elastic/connectors-python/blob/ece71a94c87d0b39cfe8286fc3ad51e81b4155f9/connectors/tests/test_source.py#L551-L554

Do you think it's worth having tests on the individual methods themselves?

**Review by artem-shelkovnikov — APPROVED** [review]
Ah I see. I normally prefer having tests per method in cases when methods are reasonably large/complex. Validation methods are amazing in this sense. I'll stamp the approval now and we can refactor tests later if needed.

**Comment by navarone-feekery** [comment]
@artem-shelkovnikov can you re-review this please? I had to update tests after merging main in.

**Review by artem-shelkovnikov — APPROVED** [review]

**Pull request merged**
