### PR TITLE
Log service version once real service starts

### PR DESCRIPTION
**Pull request by artem-shelkovnikov**
## Closes https://github.com/elastic/connectors-python/issues/614

When running connector service with default arguments OR not with "list" action, we want to output service version into console.

Example output with this change:

```
artemshelkovnikov@Artems-MacBook-Pro connectors-py % make run
bin/elastic-ingest
[FMWK][14:36:39][INFO] Loading config from /Users/artemshelkovnikov/git_tree/connectors-py/connectors/../config.yml
[FMWK][14:36:39][INFO] Running connector service version 8.8.0.0
[FMWK][14:36:39][INFO] Preflight checks...
[FMWK][14:36:39][INFO] Waiting for NodeConfig(scheme='http', host='localhost', port=9200, path_prefix='', headers={}, connections_per_node=10, request_timeout=10.0, http_compress=False, verify_certs=True, ca_certs=None, client_cert=None, client_key=None, ssl_assert_hostname=None, ssl_assert_fingerprint=None, ssl_version=None, ssl_context=None, ssl_show_warn=True, _extras={}) (so far: 0 secs)
[FMWK][14:36:40][INFO] Service started, listening to events from http://localhost:9200
[FMWK][14:36:40][INFO] Successfully started Job cleanup task...
[FMWK][14:36:40][INFO] Start cleaning up orphaned jobs...
[FMWK][14:36:40][INFO] No orphaned jobs found. Skipping...
...
```

#### Pre-Review Checklist
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)

### CODE REVIEW

**Comment by artem-shelkovnikov** [comment]
Not sure about the copy too - can it be re-phrased better?

**Review by timgrein — APPROVED** [review]
LGTM

**Comment by tarekziade** [comment]
why not with `--action list` ?

**Comment by artem-shelkovnikov** [comment]
@tarekziade mostly because if you can call with `--action list`, you can call with `--version` to get the version. This change is to show version when actually running framework.

Though I see your point and I will move the log statement up to also be shown with `--action list`

**Review by wangch079 — APPROVED** [review]

**Pull request merged**
