### PR TITLE
Make validate_config of data source call its super method first

### PR DESCRIPTION
**Pull request by wangch079**
In the `validate_config` of data source classes, it will explicitly call `self.configuration.check_valid()`, which is already implemented in `validate_config` of `BaseDataSource`. This PR makes the changes to data source classes to call `validate-config` of parent class first.

#### Pre-Review Checklist
- [x] this PR has a meaningful title
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)

### CODE REVIEW

**Comment by artem-shelkovnikov** [comment]
This PR is good, but also we need to make sure data sources don't need to even call this method and validation is done outside by the framework.

Are you planning to address this, @wangch079 ?

**Review by artem-shelkovnikov — APPROVED** [review]

**Comment by wangch079** [comment]
>but also we need to make sure data sources don't need to even call this method and validation is done outside by the framework.

Sorry, don't quite understand this statement. could you help elaborate? The config is now validated by the framework:

https://github.com/elastic/connectors-python/blob/34063b2d2597c67d2d46be8d344a9d8f85e9e2a1/connectors/sync_job_runner.py#L126

**Comment by artem-shelkovnikov** [comment]
> Sorry, don't quite understand this statement. could you help elaborate? The config is now validated by the framework:
> 
> [connectors-python/connectors/sync_job_runner.py](https://github.com/elastic/connectors-python/blob/34063b2d2597c67d2d46be8d344a9d8f85e9e2a1/connectors/sync_job_runner.py#L126)
> 
> Line 126 in [34063b2](https://github.com/elastic/connectors-python/commit/34063b2d2597c67d2d46be8d344a9d8f85e9e2a1)
> 
>  await self.data_provider.validate_config()

It would be nice to make our DataSource classes to not rely on calling `super().something`, in this case `super.validate_config()` - it's error-prone and just weird design-wise.

Instead, would be nice that the class that facilitates the work of data sources does it by itself:

```python
configuration = Configuration(connector_record['configurable_fields']) # for example

# Validate configuration fields
await configuration.validate()
data_provider = create_connector(service_type, configuration)

# Now ask connector to do its special validation
await self.data_provider.validate_config()
```

**Comment by artem-shelkovnikov** [comment]
Found this issue that I filed that explains it: https://github.com/elastic/connectors-python/issues/1194

**Comment by wangch079** [comment]
Noted. Let's address it in that issue.

**Pull request merged**
