### PR TITLE
Make MySQL connector terminate faster when connector is retrying

### PR DESCRIPTION
**Pull request by artem-shelkovnikov**
Small fix for a sleep line in MySQL connector:

```
RETRY_INTERVAL = 2

await asyncio.sleep(RETRY_INTERVAL**retry)
```

Retry count is user's input. What it means is that if something goes wrong and connector has to retry, let's say, 5 times, last sleep will be 2^5 = 32 seconds. If service is interrupted during this time, it'll have to wait until these 32 seconds pass.

This change makes use of CancellableSleep so that if service is stopped, user won't have to wait for remaining sleep time until service is interrupted.

#### Pre-Review Checklist
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)

### CODE REVIEW

**Review by timgrein — APPROVED** [review]
LGTM, we could think about incorporating this change into `retryable` under `utils.py` and an option that the sleep between retries can be cancellable.

**Comment by artem-shelkovnikov** [comment]
Created issue: https://github.com/elastic/enterprise-search-team/issues/4016

**Comment by artem-shelkovnikov** [comment]
@wangch079 I see you dismissed the review, should I fix something?

**Review by timgrein — APPROVED** [review]

**Comment by timgrein** [comment]
Reapproved, I guess @wangch079 you've dismissed it, because it was stale? Or should something else be addressed in this PR?

**Review by wangch079 — DISMISSED** [review]
I don't remember that I dismissed the approval. 🤔 

It's a good practice to use `CancellableSleeps`, and it also makes sense to use it for all native connectors.

But it's still the implementation details of each connector. What we are doing in framework-level, is to `await data_provider.close()` in the `finally` block. And this can still happen for a custom-built connector.

Anyway, I might be overthinking, the developer should be responsible for the behaviour of his/her own connector. We just need to make sure whatever goes to `main` follow the best practice.

LGTM

**Review by wangch079 — APPROVED** [review]

**Comment by artem-shelkovnikov** [comment]
I think we need to add `CancellableSleeps` to BaseConnector later and encourage usage of it to the developers of connectors - we can review current connectors for it later as well.

**Comment by wangch079** [comment]
Approved again.

Is it really a good idea to always dismiss the previous approval even for a forced commit? cc @elastic/ingestion-team 

This is particularly troublesome considering we are located across multiple time zones. When you need something to be merged so that you can proceed, you may find no one is online.

**Comment by wangch079** [comment]
>Have you faced similar problems by chance?

When I say `you may find no one is online`, that is normally me. But I don't face this problem now as recently I almost worked half in the CET time zone and half in PT time zone😅

**Comment by artem-shelkovnikov** [comment]
Okay looks like it's not easily backportable, but it's not a big problem that it's not in 8.7 either, so I'm giving up backporting for sake of simplicity.

**Pull request merged**
