### PR TITLE
[DOCS] Remove connectors info, link to elastic.co docs

### PR DESCRIPTION
**Pull request by leemthompo**
For 8.7, we ported over the connector client information in `DEVELOPING.MD` to the [Enterprise Search docs](https://www.elastic.co/guide/en/enterprise-search/8.7/connectors.html#connectors-build).

This PR removes this information from `DEVELOPING.MD` and links to the main docs, which is now the canonical documentation for these connectors.

ℹ️ I'm not sure about how the backport labels work in this repo!

Also I'll need to edit the links to the docs repo on the backport PR to use `8.7` instead of `master`.

### CODE REVIEW

**Comment by timgrein** [comment]
buildkite test this

**Comment by timgrein** [comment]
I think we need to add a version prefixed with `v` as the backport regex expects it to start with `v`: `"^v(\\d+).(\\d+)(.\\d+)+$":` "$1.$2".
`

**Comment by timgrein** [comment]
@leemthompo If the backport is open I think you can just edit it to point to `8.7` instead of `master`.

**Review by timgrein — APPROVED** [review]
LGTM from my side

**Review by chriscressman — APPROVED** [review]

**Comment by leemthompo** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.7|[](https://github.com/elastic/connectors-python/pull/672)|

Note: Successful backport PRs will be merged automatically after passing CI.

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
