### PR TITLE
Add colored logging

### PR DESCRIPTION
**Pull request by wangch079**
## Closes https://github.com/elastic/enterprise-search-team/issues/5187

This PR adds colored logging, so that log messages of different log levels will have different colors. This will only work in terminals, and logs for Cloud will remain unchanged.

Example output:
image

#### Pre-Review Checklist
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)

### CODE REVIEW

**Review by artem-shelkovnikov — DISMISSED** [review]
Nice! I think we also want different color for INFO and DEBUG - what do you think @wangch079 ?

**Comment by wangch079** [comment]
> I think we also want different color for INFO and DEBUG

WDYT to print `INFO` in `green`?

**Comment by artem-shelkovnikov** [comment]
> WDYT to print INFO in green?

I think it's a good idea! Let's give it a try :)

**Comment by wangch079** [comment]
Logged info message in green: https://github.com/elastic/connectors-python/pull/1374/commits/12c68b6936ff349c1c2587d0dfbd47cc8e120d6b

image

**Pull request merged**
