### PR TITLE
[MySQL] Move "ping" method to MySQLClient

### PR DESCRIPTION
**Pull request by timgrein**
## Follow up of https://github.com/elastic/connectors-python/pull/713

This PR moved the `ping` method to the `MySQLClient`. This changed revealed some wrong mocking in three unit tests, which are also fixed with this PR as the CI would break otherwise.

#### Pre-Review Checklist
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)
~- [ ] Considered corresponding documentation changes~
~- [ ] Contributed any configuration settings changes to the configuration reference~

### CODE REVIEW

**Comment by wangch079** [comment]
I see this pattern is used in many places:
```python
async with self.with_connection_pool() as connection_pool:
    try:
        async with connection_pool.acquire() as connection:
            ...
    except Exception:
        logger.exception("Error while connecting to the MySQL Server.")
        raise
```

Possible to extract it to `MySQLClient`?

**Comment by timgrein** [comment]
> Hmmm actually I'm not super sure about the abstraction chosen - what's the benefit of having MySQL client here? It looks now like it's just a wrapper around `with_connection_pool`

@artem-shelkovnikov It will provide more high-level methods, which are easier to use later on with the new advanced rules for MySQL. The current structure makes it very hard to do the changes needed as too many concerns are mixed IMO. It should also act as an example for other SQL-like connectors. Other data sources like `Confluence` and `Jira` showed during reviews, that it's way easier to understand the code, if the interaction with the remote API is encapsulated in a client class.

**Comment by timgrein** [comment]
@wangch079 Yes, that's the plan, see: https://github.com/elastic/connectors-python/pull/713#discussion_r1156018617

**Comment by timgrein** [comment]
buildkite test this

**Pull request merged**
