### PR TITLE
[Docs] Move connector protocol to python

### PR DESCRIPTION
**Pull request by timgrein**
I think it makes more sense to have the connector protocol in the python repository as we're moving onwards with python.

TODOs:
- [ ] Change links in ent-search docs
- [ ] Change links in connectors-ruby
- [ ] Change links in connectors-python
- [ ] (Create a redirect in connectors-ruby?)

### CODE REVIEW

**Comment by artem-shelkovnikov** [comment]
Wanted to double check - have you changed the Ruby protocol file to point here instead?

**Comment by tarekziade** [comment]
@timgrein can you create a patch in ruby where you keep the old file and add a link to the new one -- we have links out there on that location, thanks

**Comment by timgrein** [comment]
Will do that, thanks for pointing out. Will also check with docs team where we point from the official docs to the protocol.

**Comment by leemthompo** [comment]
A quick ripgrep of **enterprise-search-pubs** for `https://github.com/elastic/connectors-ruby/blob/main/docs/CONNECTOR_PROTOCOL.md` shows we don't link to this doc currently in the Enterprise Search docs

**Review by tarekziade — APPROVED** [review]

**Comment by leemthompo** [comment]
Just thinking out loud but do we have links in blogs to this file that should be redirected?

**Comment by tarekziade** [comment]
> Just thinking out loud but do we have links in blogs to this file that should be redirected?

I thought about https://www.elastic.co/blog/bring-your-own-enterprise-search-connector but nope

**Pull request merged**
