### PR TITLE
Use None instead of empty string for datetime field

### PR DESCRIPTION
**Pull request by wangch079**
This PR updates the ftest connector data, to use `None` instead of `""` for datetime fields 

#### Pre-Review Checklist
- [ ] Covered the changes with automated tests
- [x] Tested the changes locally by running `make test` and `make ftest NAME=mysql`
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)
- [ ] Considered corresponding documentation changes
- [ ] Contributed any configuration settings changes to the configuration reference

### CODE REVIEW

**Comment by tarekziade** [comment]
afaik `main` works without this change, I am curious to know why the problem appeared in your branch at https://github.com/elastic/connectors-python/pull/375 and this change fixes it?

**Comment by wangch079** [comment]
> afaik `main` works without this change, I am curious to know why the problem appeared in your branch at #375 and this change fixes it?

It breaks because I introduced this:
https://github.com/elastic/connectors-python/blob/d19c7d923438a6550936e584c8557d9d5820f3a4/connectors/byoc.py#L447-L452

In `main`, it starts heartbeat and sends heartbeat periodically, which doesn't take `last_seen` into consideration. If we have multiple instances running, there will be multiple heartbeats sent:

https://github.com/elastic/connectors-python/blob/66af09843512b88f28f89746a45d45ade351095b/connectors/byoc.py#L528-L534

In #375, it checks `last_seen`, and this can make sure it works even with multiple instances:

https://github.com/elastic/connectors-python/blob/d19c7d923438a6550936e584c8557d9d5820f3a4/connectors/byoc.py#L495-L500

**Comment by wangch079** [comment]
buildkite test this

**Comment by tarekziade** [comment]
gotcha! in that case we probably want to replace

```
last_seen = self.get("last_seen")
```

by 

```
last_seen = self["last_seen"]
```

in your patch -- because I don't think the protocol allows anything but a date field, and I don't think it's mandatory

**Comment by wangch079** [comment]
> because I don't think the protocol allows anything but a date field, 

That's right. But in our ftest, we don't have mappings:

https://github.com/elastic/connectors-python/blob/66af09843512b88f28f89746a45d45ade351095b/connectors/kibana.py#L177

>and I think it's mandatory

Not mandatory, it's `NULL` initially before the first heartbeat.

That's why I will prefer `self.get("last_seen")` instead of `self["last_seen"]`, which will raise `KeyError` if it's not available.

**Review by tarekziade — APPROVED** [review]

**Pull request merged**
