### PR TITLE
Add custom certificate authority

### PR DESCRIPTION
**Pull request by parth-crest**
## Closes https://github.com/elastic/connectors-py/issues/232

- Added support for custom certificate for secure connection 
- Changed magic method calls & updated outdated logger for inaccessible table
- Refactor query formatting
- Added default constant for certificate for now but we can eliminate once it can be configured from the UI

#### Pre-Review Checklist
- [X] Covered the changes with automated tests
- [x] Tested the changes locally

## Related Pull Requests
https://github.com/elastic/connectors-python/pull/241

### CODE REVIEW

**Comment by praveen-elastic** [comment]
buildkite test this

**Comment by parth-crest** [comment]
Updated _connect() as @tarekziade suggested [Here](https://github.com/elastic/connectors-python/pull/241#issuecomment-1351768294)

**Comment by praveen-elastic** [comment]
buildkite test this

**Review by tarekziade — APPROVED** [review]
Looks good, thanks!

**Comment by tarekziade** [comment]
buildkite test this

**Pull request merged**
