### PR TITLE
Update the autogenerated files

### PR DESCRIPTION
**Pull request by artem-shelkovnikov**
This PR updates automatically generated files.

Why did I do this? I ran `make clean && make run` and as a result of this command the files in this PR were updated. I believe these files are autogenerated and are not generated unless a clean reinstall is done, thus they were not updated.

cc @tarekziade - is this logic correct? Intuitively, the logic to generate these files automatically should run with each re-run.

### CODE REVIEW

**Comment by tarekziade** [comment]
something is very odd here. those are files from the `base64io` project, not our files... it looks like the installation of `base64io` is buggy, as it creates those files in the root.

I can confirm it's a problem on their side, see https://github.com/aws/base64io-python/issues/38

**Comment by artem-shelkovnikov** [comment]
Yeah I can see it's probably cause of this line:
https://github.com/aws/base64io-python/blob/master/setup.py#L41

Btw what is the use-case for the library? Should we swap to a different one or should I try to sumbit PR to the base64io-python first?

**Comment by tarekziade** [comment]
> Btw what is the use-case for the library?

it a fallback solution for stream-encoding base64 when you don't have `base64` on your system (win32)

https://github.com/elastic/connectors-python/blob/main/connectors/utils.py#L220

>  should I try to sumbit PR to the base64io-python first?

Yeah I would do this and see if they are responsive

**Comment by artem-shelkovnikov** [comment]
Made the PR in the package repo: https://github.com/aws/base64io-python/pull/41

**Pull request closed without merging**
