### PR TITLE
[Microsoft SQL] Update E2E as per PyTDS library 

### PR DESCRIPTION
**Pull request by moxarth-elastic**
Change End to End testing for MS-SQL connector as per Pytds library
#### Pre-Review Checklist
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally

### CODE REVIEW

**Review by artem-shelkovnikov — APPROVED** [review]

**Comment by artem-shelkovnikov** [comment]
@moxarth-elastic do you think it's good to merge?

**Comment by moxarth-elastic** [comment]
> @moxarth-elastic do you think it's good to merge?

Yes, we can merge this PR.

**Comment by danajuratoni** [comment]
Is this PR for https://github.com/elastic/connectors-python/issues/623?

**Comment by moxarth-elastic** [comment]
> Is this PR for #623?

Yes, It's for issue #623

**Pull request merged**
