### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by Mohsin-Ul-Islam**
Fixes a typo in `docs/DEVELOPER.md`

#### Pre-Review Checklist
- [ ] Covered the changes with automated tests
- [ ] Tested the changes locally

## Release Note
Fix a typo in `docs/DEVELOPER.md`

### CODE REVIEW

**Comment by tarekziade** [comment]
Thanks @Mohsin-Ul-Islam -- I'll be able to merge once you've signed the CLA the CI bot checks

**Comment by Mohsin-Ul-Islam** [comment]
@tarekziade I signed the CLA. Do you please rerun the CI check to verify.

**Comment by tarekziade** [comment]
buildkite test this

**Comment by tarekziade** [comment]
Thanks for your contribution

**Review by tarekziade — APPROVED** [review]

**Pull request merged**
