### PR TITLE
Add xlsb, xlsm in tika supported filetypes

### PR DESCRIPTION
**Pull request by praveen-elastic**
## Closes https://github.com/elastic/connectors-py/issues/892

Add XLSM and XLSB filetypes to the list `TIKA_SUPPORTED_FILETYPES` in utils.py

#### Pre-Review Checklist
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)
- [x] Considered corresponding documentation changes [ ] New external service dependencies added.

### CODE REVIEW

**Comment by praveen-elastic** [comment]
buildkite test this

**Review by timgrein — APPROVED** [review]
LGTM

**Comment by efegurkan** [comment]
backport --pr 894 --autoMerge --autoMergeMethod squash

**Comment by efegurkan** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.8|[](https://github.com/elastic/connectors-python/pull/906)|

Note: Successful backport PRs will be merged automatically after passing CI.

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
