### PR TITLE
[Dropbox] Implement E2E Feature

### PR DESCRIPTION
**Pull request by moxarth-elastic**
## Closes https://github.com/elastic/connectors-python/issues/1232

This PR includes functional tests for Dropbox connector using Flask module.

#### Pre-Review Checklist
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] if there is no GH issue, please create it. Each PR should have a link to an issue
- [x] this PR has a thorough description
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)

### CODE REVIEW

**Review by seanstory — APPROVED** [review]

**Comment by seanstory** [comment]
Have you actually run this? I can't find a job history for it on buildkite.

**Comment by moxarth-elastic** [comment]
> Have you actually run this? I can't find a job history for it on buildkite.

Yes, I ran it locally, I created this PR from a fork, so the buildkite job won't exist for the branch on forked repositories that's why you can't find job history.

**Comment by seanstory** [comment]
It seems that this did not add dropbox to the nightly build. Is that expected?

**Comment by seanstory** [comment]
looks like `.buildkite/nightly_steps.yml` needs to be updated.

**Pull request merged**
