### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by tarekziade**
be explicit about runing `make ftest`

#### Pre-Review Checklist
- [ ] Covered the changes with automated tests
- [ ] Tested the changes locally
- [ ] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)
- [ ] Considered corresponding documentation changes
- [ ] Contributed any configuration settings changes to the configuration reference

#### Changes Requiring Extra Attention

- [ ] Security-related changes (encryption, TLS, SSRF, etc)
- [ ] New external service dependencies added.

### CODE REVIEW

**Review by wangch079 — APPROVED** [review]

**Comment by seanstory** [comment]
Why don't we just have CI run tests, and block the PR if they fail?

**Comment by tarekziade** [comment]
the CI runs the tests, but the e2e tests are running as nightlies because they take a while. the intent is to add a small one to improve this https://github.com/elastic/connectors-python/issues/428

But the expectation is that when you change the code, you test that it really works before you ask for a review.
and running `make ftest NAME=mysql` does a full e2e test that verifies the service can still index data in Elasticsearch

**Comment by seanstory** [comment]
I'm looking at it from the angle that if we have a TODO list, we can automate it and _ensure_ it is done, or we can make a manual task list and _hope_ that it gets done. If we want PRs to have run `make ftest NAME=mysql` before they get merged, we should just automate that.

**Comment by tarekziade** [comment]
well `Tested the changes locally` is pretty vague. Here we're hinting at what you should do as a dev.

But I don't expect you to run `make ftest` if you know you did not change the syncing mechanism in the patch.
Maybe we can say:

`Tested the changes locally -- make sure you try an e2e test if you change the sync mechanism or a data source class`

**Pull request merged**
